# RDF解析プログラムのMakefile

# ターゲットプログラム名
TARGET = rdf

# lammpsio.modファイルをコピー
$(shell cp ../../src/LammpsDumpReader/fortran/lammpsio.mod . 2>/dev/null || true)

# 共通Makefileをインクルード
include ../../Makefile.common
